definitions:
  outputdata.Community:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
      owner:
        $ref: '#/definitions/outputdata.User'
        type: object
    type: object
  outputdata.Login:
    properties:
      jwt:
        type: string
      user:
        $ref: '#/definitions/outputdata.User'
        type: object
    type: object
  outputdata.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: 192.168.50.10:8080
info:
  contact: {}
  description: This is a personal project
  license:
    name: takaaki12353491
  title: Service API
  version: "1.0"
paths:
  /communities:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: jwt token
        in: header
        name: Authorization
        required: true
        type: string
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: description
        in: formData
        name: description
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/outputdata.Community'
        "400":
          description: Bad Request
          schema:
            type: string
      tags:
      - Community
  /login:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: identity
        in: formData
        name: identity
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/outputdata.Login'
        "409":
          description: Conflict
          schema:
            type: string
      summary: Login
      tags:
      - Auth
  /signup:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: name
        in: formData
        name: name
        required: true
        type: string
      - description: email
        in: formData
        name: email
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "400": {}
      tags:
      - Auth
swagger: "2.0"
